### ISSUE TITLE
UWUResponse

### ISSUE THREAD

**Issue by IKanraI** [IKanraI/Gaiza#29]
Still sometimes gives a stacktrace of null pointer

**Comment by IKanraI** [comment]
java.lang.NullPointerException
        at listener.UwuResponse.lambda$0(UwuResponse.java:61)
        at org.javacord.core.util.event.EventDispatcher.lambda$dispatchMessageCreateEvent$95(EventDispatcher.java:3413)
        at org.javacord.core.util.event.EventDispatcherBase.lambda$dispatchEvent$10(EventDispatcherBase.java:197)
        at org.javacord.core.util.event.EventDispatcherBase.lambda$checkRunningListenersAndStartIfPossible$18(EventDispatcherBase.java:265)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

**Comment by IKanraI** [comment]
patch made today in attempt to fix the issue. Sent to live

**Comment by IKanraI** [comment]
current monitoring on the issue there seems to be no more thrown null pointers and had to do a bugfix that the bot was sending a response every time a three letter word was sent

**Comment by IKanraI** [comment]
No more null pointers thrown from uwuresponse
